# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '--tag=gcr.io/$PROJECT_ID/gcloud', '-f', 'Dockerfile', '.']

# # Simple sanity check: invoke the new gcloud container to confirm that it was
# # built correctly.
# - name: 'gcr.io/$PROJECT_ID/gcloud'
#   args: ['info']

# # Confirm that auth is piped through correctly.
# - name: 'gcr.io/$PROJECT_ID/gcloud'
#   args: ['builds', 'list']

# images:
# - 'gcr.io/$PROJECT_ID/gcloud'

steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcloud', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gcloud']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'raisedanchor', '--image', 'gcr.io/$PROJECT_ID/gcloud', '--region', 'us-central1']
images:
- gcr.io/$PROJECT_ID/gcloud
timeout: 2400s